name: App build

on:
    push: 
      branches: [ main ]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          flake8 .