name: DevSecOps CI/CD Pipeline
on:
  push:
    branches:
      - main

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  test:
   needs: lint
   uses: ./.github/workflows/test.yml

  artifact:
   needs: test
   uses: ./.github/workflows/build.yml

  dokcer-push:
   needs: [lint, test, artifact, docker-build-push]
   uses: ./.github/workflows/docker.yml
   secrets: inherit

  scan:
   needs: [lint, test, docker-build-push]
   uses: ./.github/workflows/security-scan.yml
   secrets: inherit



  deploy:
   needs: [lint, docker-build, scan, push]
   uses: ./.github/workflows/deploy.yml
   secrets: inherit