name: Docker Image Scan

on:
    workflow_run:
        workflows: ["Build Artifact"]
        types:
            - completed
jobs:
    images-scan:
        runs-on: ubuntu-latest


        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Build Docker Image
              run: |
               docker build -t python-app:latest .

            - name: Trivy vulnerability Scan Docker Image
              uses: aquasecurity/trivy-action@0.35.0
              with:
                image-ref: "python-app:latest"
                format: "table"
                severity: "CRITICAL"
                exit-code: "0"